version: "3.7"

services:

  assistant:
    image: "dainst/bibliography-assistant"
    ports:
      - "4300:4000"
    networks:
      - web
      - default
    deploy:
      labels:
        - "traefik.docker.network=web"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:bibliography-assistant.idai.world"
        - "traefik.port=4000"

networks:
  web:
    external: true