version: "3.7"

services:

  assistant:
    image: "dainst/bibliography-assistant"
    ports:
      - "4300:4000"
    volumes:
      - "assistant-config:/opt/src/assistant/config"
    networks:
      - web
      - default
    deploy:
      labels:
        - "traefik.docker.network=web"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:bibliography-assistant.idai.world"
        - "traefik.port=4000"

  anystyle:
    image: "dainst/anystyle-sinatra"
    networks:
      - default
    ports:
      - "4567:4567"

  grobid:
      image: "lfoppiano/grobid:0.7.0"
      networks:
      - default
      ports:
        - "8070:8070"

volumes:
  assistant-config:

networks:
  web:
    external: true
