version: "3.7"

services:

  assistant:
    image: "dainst/bibliography-assistant"
    build: "./assistant"
    ports:
      - "4000:4000"

  anystyle:
    image: "dainst/anystyle-sinatra"
    build: "./anystyle"
    ports:
      - "4567:4567"

  grobid:
    image: "lfoppiano/grobid:0.7.0"
    ports:
      - "8070:8070"

  cermine:
    image: "elifesciences/cermine:1.13"
    ports:
      - "8072:8080"
